---
title: "CLASES"
author: "Julian Andres Gomez Piedrahita/Mateo Martinez Vargas"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: journal
    toc: true
    toc_float: true
---


# INSTALACION

BLA BLA BLA (LINK R Y RSTUDIO)

# CARGA DE BASES DE DATOS

Existen diferentes tipos de carga de datos para distintos archivo como por ejemplo, excel (xlsx), csv (separado por comas), txt (Archivos textuales)


```{r}
#read.csv("url", sep = , o tabulacion o : ) #csv
#read.table() #txt
#read.xlsx() # excel


#y organizarla (colocarle de los nombrres de columna header = True, nombres filas quitarse, row.names(false),  )
```


Ejercicio carga base de datos con csv
Vamos poner de ejemplo la base de datos de calidad del agua del rio ....

```{r,include = TRUE,echo=TRUE}
datos<- read.csv("datos_amoniaco.csv")
datos
```



Estes e el codigo para....
```{r,include=TRUE,echo=TRUE}

# Vector original
x <- c(5, 7, 8, 9, 2, 3)

# Convertir el vector en una matriz de 2x3
matriz <- matrix(x, nrow = 2, byrow = TRUE)

# Mostrar la matriz resultante
matriz

```

Este es el otro codigo 
## CODIGO 1.1
```{r}

#codigo

```

